-- CreateTable
CREATE TABLE "CourseSchedule" (
    "courseID" INTEGER NOT NULL,
    "termCode" INTEGER NOT NULL,
    "session" TEXT NOT NULL,
    "subject" TEXT NOT NULL,
    "catalog" TEXT NOT NULL,
    "section" TEXT NOT NULL,
    "componentCode" TEXT NOT NULL,
    "componentDescription" TEXT NOT NULL,
    "classNumber" INTEGER NOT NULL,
    "classAssociation" INTEGER NOT NULL,
    "courseTitle" TEXT NOT NULL,
    "topicID" INTEGER NOT NULL,
    "topicDescription" TEXT NOT NULL,
    "classStatus" TEXT NOT NULL,
    "locationCode" TEXT NOT NULL,
    "instructionModeCode" TEXT NOT NULL,
    "instructionModeDescription" TEXT NOT NULL,
    "meetingPatternNumber" INTEGER NOT NULL,
    "roomCode" TEXT NOT NULL,
    "buildingCode" TEXT NOT NULL,
    "room" TEXT NOT NULL,
    "classStartTime" TEXT NOT NULL,
    "classEndTime" TEXT NOT NULL,
    "modays" TEXT NOT NULL,
    "tuesdays" TEXT NOT NULL,
    "wednesdays" TEXT NOT NULL,
    "thursdays" TEXT NOT NULL,
    "fridays" TEXT NOT NULL,
    "saturdays" TEXT NOT NULL,
    "sundays" TEXT NOT NULL,
    "classStartDate" TEXT NOT NULL,
    "classEndDate" TEXT NOT NULL,
    "career" TEXT NOT NULL,
    "departmentCode" TEXT NOT NULL,
    "departmentDescription" TEXT NOT NULL,
    "facultyCode" TEXT NOT NULL,
    "facultyDescription" TEXT NOT NULL,
    "enrollmentCapacity" INTEGER NOT NULL,
    "currentEnrollment" TEXT NOT NULL,
    "waitlistCapacity" INTEGER NOT NULL,
    "currentWaitlistTotal" TEXT NOT NULL,
    "hasSeatReserved" TEXT NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "CourseSchedule_subject_catalog_termCode_section_meetingPatternNumber_key" ON "CourseSchedule"("subject", "catalog", "termCode", "section", "meetingPatternNumber");
